source "http://rubygems.org"

gemspec :path => "../../"

gem "rails",            "~> 3.1.1"
gem "sqlite3-ruby",     "~> 1.3.3"
gem "will_paginate",    "~> 3.0.2"

group :test do
  gem "capybara",         "~> 1.1.1"
  gem "cucumber",         "~> 1.1.0"
  gem "cucumber-rails",   "~> 1.1.1"
  gem "database_cleaner", "~> 0.6.7"
  gem "cucumber-rails-training-wheels"
end
