lib = File.expand_path('../../../lib', __FILE__)
$:.unshift lib unless $:.include?(lib)

gemspec :path => "../../"

gem "rails",            "~> 3.0.1"
gem "sqlite3-ruby",     "~> 1.3.0"
gem "will_paginate",    "~> 3.0.pre2"

group :test do
  gem 'rspec-rails',      "~> 2.0.1"
  gem "capybara",         "~> 0.4.0"
  gem "cucumber",         "~> 0.9.3"
  gem "cucumber-rails",   "~> 0.3.2"
  gem "database_cleaner", "~> 0.6.0"
end
