lib = File.expand_path('../../../lib', __FILE__)
$:.unshift lib unless $:.include?(lib)

gemspec :path => '../../'

gem "rails",            "~> 2.3.10"
gem "sqlite3-ruby",     "~> 1.3.0"
gem "will_paginate",    "~> 2.3.14"

group :test do
  gem "capybara",         "~> 0.3.9"
  gem "cucumber",         "~> 0.9.3"
  gem "cucumber-rails",   "~> 0.3.2"
  gem "database_cleaner", "~> 0.5.2"
end
